name: Flask CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Flask server (for testing purposes, in a real workflow use pytest or other tools for testing)
      - name: Run Flask app
        env:
          FLASK_APP: app.py  # Ensure your Flask app's entry point matches
          FLASK_ENV: development
        run: flask run --host=0.0.0.0 --port=8000
